all: compile run clean

compile:
	@echo "Compilando Les Petit Poissons"
	@gcc -Wall -o parte_2 parte_2.c

run:
	@echo "Ejecutando Les Petit Poissons"
	@./parte_2

clean:
	@echo "Limpiando"
	@rm parte_2
