all: ejercicio1 ejercicio2 ejercicio3 ejercicio4 ejercicio5 ejercicio6 ejercicio7 ejercicio8

ejercicio1:
	@echo "Compilando ejercicio 1"
	@gcc -Wall -o ejercicio1-1 ejercicio1-1.c

ejercicio2:
	@echo "Compilando ejercicio 2"
	@gcc -Wall -o ejercicio2-2 ejercicio2-2.c

ejercicio3:
	@echo "Compilando ejercicio 3-2"
	@gcc -Wall -o ejercicio3-2 ejercicio3-2.c
	@echo "Compilando ejercicio 3-3-1"
	@gcc -Wall -o ejercicio3-3-1 ejercicio3-3-1.c
	@echo "Compilando ejercicio 3-3-2"
	@gcc -Wall -o ejercicio3-3-2 ejercicio3-3-2.c
	@echo "Compilando ejercicio 3-3-3"
	@gcc -Wall -o ejercicio3-3-3 ejercicio3-3-3.c

ejercicio4:
	@echo "Compilando ejercicio 4-2"
	@gcc -Wall -o ejercicio4-2 ejercicio4-2.c
	@echo "Compilando ejercicio 4-3"
	@gcc -Wall -o ejercicio4-3 ejercicio4-3.c

ejercicio5:
	@echo "Compilando ejercicio 5"
	@gcc -Wall -o ejercicio5-1 ejercicio5-1.c

ejercicio6:
	@echo "Compilando ejercicio 6"
	@gcc -Wall -o ejercicio6-1 ejercicio6-1.c

ejercicio7:
	@echo "Compilando ejercicio 7"
	@gcc -Wall -o ejercicio7-1 ejercicio7-1.c

ejercicio8:
	@echo "Compilando ejercicio 8"
	@gcc -Wall -o ejercicio8-1 ejercicio8-1.c

clean:
	@rm ejercicio1-1
	@rm ejercicio2-2
	@rm ejercicio3-2
	@rm ejercicio3-3-1
	@rm ejercicio3-3-2
	@rm ejercicio3-3-3
	@rm ejercicio4-2
	@rm ejercicio4-3
	@rm ejercicio5-1
	@rm ejercicio6-1
	@rm ejercicio7-1
	@rm ejercicio8-1
	@echo "Limipiando..."
