all: compile run clean

compile:
	@echo "Compilando Les Petit Poissons"
	@gcc -Wall -o parte_1 parte_1.c -pthread

run:
	@echo "Ejecutando Les Petit Poissons"
	@./parte_1

clean:
	@echo "Limpiando"
	@rm parte_1
